### ISSUE TITLE
Managed Kubernetes not supported zone error

### ISSUE THREAD

**Issue by paolomainardi** [terraform-providers/terraform-provider-alicloud#1097]
### Terraform Version

```
+ Terraform v0.11.7
+ provider.alicloud v1.40.0
+ provider.kubernetes v1.6.2
````

### Affected Resource(s)

- alicloud_cs_managed_kubernetes

### Terraform Configuration Files
```hcl

variable "instance_type_family" {
  default = "ecs.sn1ne" # 2 cpu
}
variable "available_instance_type" {
  default = "ecs.sn1ne.large" # # 2cpu - 4GB RAM - Network enhanced
}

data "alicloud_zones" main {
  available_resource_creation = "Rds"
  enable_details = true
  available_instance_type = "${var.available_instance_type}"
  output_file = "./outputs/alicloud_zones"
}

data "alicloud_instance_types" "default" {
    availability_zone = "${data.alicloud_zones.main.zones.0.id}"
    cpu_core_count = "${var.cpu_core_count}"
    memory_size = "${var.memory_size}"
    instance_type_family = "${var.instance_type_family}"
    kubernetes_node_role = "Worker"
    is_outdated = "false"
    network_type = "Vpc"
    output_file = "./outputs/alicloud_instance_types"
}

resource "alicloud_key_pair" "k8s" {
    key_name = "aliyun_k8s_key_pair"
    key_file = "../keys/aliyun-k8s-key-pair"
}

// If there is not specifying vpc_id, the module will launch a new vpc
resource "alicloud_vpc" "vpc" {
  count      = "${var.vpc_id == "" ? 1 : 0}"
  cidr_block = "${var.vpc_cidr}"
  name       = "${var.vpc_name == "" ? var.example_name : var.vpc_name}"
}

// According to the vswitch cidr blocks to launch several vswitches
resource "alicloud_vswitch" "vswitches" {
  count             = "${length(var.vswitch_ids) > 0 ? 0 : length(var.vswitch_cidrs)}"
  vpc_id            = "${var.vpc_id == "" ? join("", alicloud_vpc.vpc.*.id) : var.vpc_id}"
  cidr_block        = "${element(var.vswitch_cidrs, count.index)}"
  availability_zone = "${lookup(data.alicloud_zones.main.zones[count.index%length(data.alicloud_zones.main.zones)], "id")}"
  name              = "${var.vswitch_name_prefix == "" ? format("%s-%s", var.example_name, format(var.number_format, count.index+1)) : format("%s-%s", var.vswitch_name_prefix, format(var.number_format, count.index+1))}"
}

resource "alicloud_nat_gateway" "default" {
  count  = "${var.new_nat_gateway == true ? 1 : 0}"
  vpc_id = "${var.vpc_id == "" ? join("", alicloud_vpc.vpc.*.id) : var.vpc_id}"
  name   = "${var.example_name}"
  specification = "Small"
}

resource "alicloud_eip" "default" {
  count     = "${var.new_nat_gateway == "true" ? 1 : 0}"
  bandwidth = "${var.eip_bandwidth}"
}

resource "alicloud_eip_association" "default" {
  count         = "${var.new_nat_gateway == "true" ? 1 : 0}"
  allocation_id = "${alicloud_eip.default.id}"
  instance_id   = "${alicloud_nat_gateway.default.id}"
}

resource "alicloud_snat_entry" "default" {
  count             = "${var.new_nat_gateway == "false" ? 0 : length(var.vswitch_ids) > 0 ? length(var.vswitch_ids) : length(var.vswitch_cidrs)}"
  snat_table_id     = "${alicloud_nat_gateway.default.snat_table_ids}"
  source_vswitch_id = "${length(var.vswitch_ids) > 0 ? element(split(",", join(",", var.vswitch_ids)), count.index%length(split(",", join(",", var.vswitch_ids)))) : length(var.vswitch_cidrs) < 1 ? "" : element(split(",", join(",", alicloud_vswitch.vswitches.*.id)), count.index%length(split(",", join(",", alicloud_vswitch.vswitches.*.id))))}"
  snat_ip           = "${alicloud_eip.default.ip_address}"
}

resource "alicloud_cs_managed_kubernetes" "k8s" {
  name = "${var.name}"
  availability_zone = "${data.alicloud_zones.main.zones.0.id}"
  new_nat_gateway = false
  vswitch_ids = ["${length(var.vswitch_ids) > 0 ? element(split(",", join(",", var.vswitch_ids)), count.index%length(split(",", join(",", var.vswitch_ids)))) : length(var.vswitch_cidrs) < 1 ? "" : element(split(",", join(",", alicloud_vswitch.vswitches.*.id)), count.index%length(split(",", join(",", alicloud_vswitch.vswitches.*.id))))}"]
  worker_instance_types = ["${data.alicloud_instance_types.default.instance_types.0.id}"]
  worker_numbers = "${var.k8s_worker_number}"
  key_name = "${alicloud_key_pair.k8s.key_name}"
  pod_cidr = "172.20.0.0/16"
  service_cidr = "172.21.0.0/20"
  install_cloud_monitor = true
  slb_internet_enabled = true
  worker_disk_category  = "${var.k8s_worker_disk_category}"
  worker_disk_size  = "${var.k8s_worker_disk_size}"
  worker_data_disk_size = "${var.k8s_worker_data_disk_size}"
  worker_data_disk_category = "${var.k8s_worker_data_disk_category}"
  worker_instance_charge_type = "${var.k8s_worker_instance_charge_type}"
  worker_period_unit = "${var.k8s_worker_period_unit}"
  worker_period = "${var.k8s_worker_period}"
  worker_auto_renew = "${var.k8s_worker_auto_renew}"
  worker_auto_renew_period = "${var.k8s_worker_auto_renew_period}"
}

```

### Debug Output

```
alicloud_cs_managed_kubernetes.k8s: Creating...
  availability_zone:           "" => "cn-beijing-c"
  install_cloud_monitor:       "" => "true"
  key_name:                    "" => "aliyun_k8s_key_pair"
  name:                        "" => "caleffi-k8s"
  name_prefix:                 "" => "Terraform-Creation"
  new_nat_gateway:             "" => "false"
  pod_cidr:                    "" => "172.20.0.0/16"                                                                                                                                       security_group_id:           "" => "<computed>"                                                                                                                                          service_cidr:                "" => "172.21.0.0/20"
  slb_internet_enabled:        "" => "true"
  vpc_id:                      "" => "<computed>"
  vswitch_ids.#:               "" => "1"
  vswitch_ids.0:               "" => "vsw-2zedqkn5mi17navne7r0a"
  worker_data_disk_category:   "" => "cloud_efficiency"
  worker_data_disk_size:       "" => "100"
  worker_disk_category:        "" => "cloud_efficiency"
  worker_disk_size:            "" => "100"
  worker_instance_charge_type: "" => "PostPaid"
  worker_instance_types.#:     "" => "1"
  worker_instance_types.0:     "" => "ecs.sn1ne.large"
  worker_nodes.#:              "" => "<computed>"
  worker_numbers.#:            "" => "1"
  worker_numbers.0:            "" => "3"

Error: Error applying plan:

1 error(s) occurred:

* alicloud_cs_managed_kubernetes.k8s: 1 error(s) occurred:

* alicloud_cs_managed_kubernetes.k8s: Creating ManagedKubernetes Cluster got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"1582E61E-AA18
-434E-8755-B735E0A1F13C"}, HostId:"", Code:"ZoneNotSupported", Message:"The zone cn-beijing-c is not supported, please try other zones"}, StatusCode:400}
```

### Expected Behavior

`cn-beijing-c` it's a supported zone.

### Actual Behavior

```
* alicloud_cs_managed_kubernetes.k8s: Creating ManagedKubernetes Cluster got an error: &common.Error{ErrorResponse:common.ErrorResponse{Response:common.Response{RequestId:"1582E61E-AA18
-434E-8755-B735E0A1F13C"}, HostId:"", Code:"ZoneNotSupported", Message:"The zone cn-beijing-c is not supported, please try other zones"}, StatusCode:400}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by xh4n3** [comment]
The `ZoneNotSupported` error was returned by Container Service OpenAPI, it means SLB is sold out in this AZ, perhaps we should change an AZ.
@paolomainardi

**Comment by xiaozhu36** [comment]
HI @paolomainardi Does this issue have been fixed?

**Comment by xiaozhu36** [comment]
Closed by no reply.

**Comment by zipme** [comment]
@xiaozhu36 I don't think it's fixed, still happens to me all the time.

**Comment by xiaozhu36** [comment]
Hi . @zipme Can you show me the error details?

**Comment by zipme** [comment]
```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:323: Resource alicloud_cs_managed_kubernetes CreateKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: 4389C9D6-F20D-49E0-B305-59183AE42C70 Status Code: 400 Code: ZoneNotSupported Message: The current zone  does not support creating SLB, please try other zones
```

```
  # module.aliyun.alicloud_cs_managed_kubernetes.k8s will be created
  + resource "alicloud_cs_managed_kubernetes" "k8s" {
      + availability_zone           = "cn-beijing-a"
      + client_cert                 = "~/.kube/aliyun/client-cert.pem"
      + client_key                  = "~/.kube/aliyun/client-key.pem"
      + cluster_ca_cert             = "~/.kube/aliyun/cluster-ca-cert.pem"
      + force_update                = false
      + id                          = (known after apply)
      + install_cloud_monitor       = true
      + kube_config                 = "~/.kube/config"
      + name                        = "sumi"
      + name_prefix                 = "Terraform-Creation"
      + new_nat_gateway             = true
      + password                    = (sensitive value)
      + pod_cidr                    = "172.20.0.0/16"
      + security_group_id           = (known after apply)
      + service_cidr                = "172.21.0.0/20"
      + slb_internet_enabled        = true
      + vpc_id                      = (known after apply)
      + worker_disk_category        = "cloud_efficiency"
      + worker_disk_size            = 40
      + worker_instance_charge_type = "PostPaid"
      + worker_instance_types       = [
          + "ecs.n1.small",
        ]
      + worker_nodes                = (known after apply)
      + worker_number               = 2
    }
```

**Comment by xiaozhu36** [comment]
@zipme Ok, thanks. I will check it with k8s team. Please be patient. cc  @menglingwei

**Comment by zipme** [comment]
@xiaozhu36 thanks!

**Comment by zipme** [comment]
Hi @xiaozhu36 , I found a workaround that by specifying `vswitch_ids` instead of `availability_zone`:
```tf
resource "alicloud_cs_managed_kubernetes" "k8s" {
  name              = "${var.name}"
  # availability_zone = "cn-beijing-c"
  vswitch_ids = ["vsw-2ze........."]
  # availability_zone     = "${data.alicloud_zones.main.zones.2.id}"
  new_nat_gateway       = true
 ...
```
The VSwitch is located at `cn-beijing-c`, so I guess SLB is still available in that zone, however if I specify 
`cn-beijing-c` for `availability_zone` explicitly it won't work still.

**Comment by mozillazg** [comment]
+1 for `ZoneNotSupported` error and workaround via specifying `vswitch_ids` :

```
2019-11-22T11:33:53.403+0800 [INFO]  plugin.terraform-provider-alicloud_v1.62.0_x4: configuring server automatic mTLS: timestamp=2019-11-22T11:33:53.403+0800
2019-11-22T11:33:53.444+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.62.0_x4: plugin address: address=/var/folders/9p/w9p_0s616x3d15xlq9p0zrpw0000gp/T/plugin871316776 network=unix timestamp=2019-11-22T11:33:53.444+0800
2019-11-22T11:33:53.444+0800 [DEBUG] plugin: using plugin: version=5
2019/11/22 11:33:53 [WARN] Provider "alicloud" produced an invalid plan for alicloud_cs_managed_kubernetes.k8s-for-report, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .slb_internet_enabled: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .force_update: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .worker_disk_category: planned value cty.StringVal("cloud_efficiency") does not match config value cty.NullVal(cty.String)
      - .worker_disk_size: planned value cty.NumberIntVal(40) does not match config value cty.NullVal(cty.Number)
      - .worker_instance_charge_type: planned value cty.StringVal("PostPaid") does not match config value cty.NullVal(cty.String)
2019/11/22 11:33:53 [TRACE] <root>: eval: *terraform.EvalCheckPlannedChange
alicloud_cs_managed_kubernetes.k8s-for-report: Creating...
2019/11/22 11:33:53 [DEBUG] alicloud_cs_managed_kubernetes.k8s-for-report: applying the planned Create change
2019/11/22 11:33:53 [TRACE] GRPCProvider: ApplyResourceChange
2019-11-22T11:33:53.573+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.62.0_x4: 2019/11/22 11:33:53 [DEBUG] setting computed for "worker_nodes" from ComputedKeys
2019/11/22 11:33:58 [DEBUG] alicloud_cs_managed_kubernetes.k8s-for-report: apply errored, but we're indicating that via the Error pointer rather than returning it: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:323: Resource alicloud_cs_managed_kubernetes CreateKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: F80166B2-F0CB-4B11-800F-30214EAD2D3A Status Code: 400 Code: ZoneNotSupported Message: The current zone  does not support creating SLB, please try other zones
2019/11/22 11:33:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/11/22 11:33:58 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:323: Resource alicloud_cs_managed_kubernetes CreateKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: F80166B2-F0CB-4B11-800F-30214EAD2D3A Status Code: 400 Code: ZoneNotSupported Message: The current zone  does not support creating SLB, please try other zones
2019/11/22 11:33:58 [ERROR] <root>: eval: *terraform.EvalSequence, err: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:323: Resource alicloud_cs_managed_kubernetes CreateKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: F80166B2-F0CB-4B11-800F-30214EAD2D3A Status Code: 400 Code: ZoneNotSupported Message: The current zone  does not support creating SLB, please try other zones
2019/11/22 11:33:58 [TRACE] [walkApply] Exiting eval tree: alicloud_cs_managed_kubernetes.k8s-for-report
2019/11/22 11:33:58 [TRACE] vertex "alicloud_cs_managed_kubernetes.k8s-for-report": visit complete

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cs_managed_kubernetes.go:323: Resource alicloud_cs_managed_kubernetes CreateKubernetesCluster Failed!!! [SDK denverdino/aliyungo ERROR]:
Aliyun API Error: RequestId: F80166B2-F0CB-4B11-800F-30214EAD2D3A Status Code: 400 Code: ZoneNotSupported Message: The current zone  does not support creating SLB, please try other zones
```

```

**Comment by xiaozhu36** [comment]
HI @zipme @mozillazg I am sorry for late. This error message has miss-leading. The actually reason is the TF template did not set `vswitch_ids`. Please specify it and have a try.

**Comment by xiaozhu36** [comment]
Closed by no reply.
