### ISSUE TITLE
RDS Alarms Error

### ISSUE THREAD

**Issue by firasnajjar** [terraform-providers/terraform-provider-alicloud#760]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

→ terraform -v
Terraform v0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_cms_alarm

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "alicloud" {
  access_key = "**********"
  secret_key = "**********"
  region = "eu-central-1"
  version = "1.30"
}

resource "alicloud_vpc" "vpc" {
  name       = "test"
  cidr_block = "10.0.0.0/8"
}

resource "alicloud_vswitch" "vsw" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.0.0/24"
  availability_zone = "eu-central-1a"
  name              = "rds_subnet"
}

resource "alicloud_db_instance" "my_postgres" {
  engine            = "PostgreSQL"
  engine_version    = "10.0"
  instance_type     = "rds.pg.t1.small"
  instance_storage  = "20"
  instance_name     = "test_postgres"
  zone_id           = "eu-central-1MAZ1(a,b)"  // in multi zones, the vswitch must be in one of the zones
  vswitch_id        = "${alicloud_vswitch.vsw.id}" // in multi zones, the vswitch must be in one of the zones
  security_ips      = ["${alicloud_vswitch.dmz.cidr_block}"]
}

//credentials for accessing the db
resource "alicloud_db_account" "my_postgres_account" {
  instance_id       = "${alicloud_db_instance.my_postgres.id}"
  name              = "blabla"   //the account name cannot have capital letters
  password          = "*********"
  description       = "creds"
}

//backup policy
resource "alicloud_db_backup_policy" "default" {
  instance_id       = "${alicloud_db_instance.my_postgres.id}"
  retention_period  = 7
  log_backup        = true
  log_retention_period = 7
}

resource "alicloud_cms_alarm" "cpu_alarm" {
  name = "some_name"
  project = "acs_rds_dashboard"
  metric = "CpuUsage"
  dimensions = {
    instanceId = "${alicloud_db_instance.my_postgres.id}"
  }
  statistics ="Average"
  period = 300
  operator = ">"
  threshold = 90
  triggered_count = 1
  contact_groups = ["some_group"]
  notify_type = 0
  enabled = true
}


resource "alicloud_vswitch" "dmz" {
  vpc_id            = "${alicloud_vpc.vpc.id}"
  cidr_block        = "10.0.1.0/24"
  availability_zone = "eu-central-1b"
  name              = "dmz_subnet"
}


```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

This is not an issue with terraform itself. It is an issue with the provider.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
There is no crash!

### Expected Behavior
What should have happened?
I shouldn't get an error if I apply the same terraform script more than once!
I shouldn't get any changes in the plan if the resources did not change in the IAAS and my scripts did not change. This is not the case with: 'notify_type'
### Actual Behavior
What actually happened?
Applying the same script more than once yields the following error:
```
* alicloud_cms_alarm.cpu_alarm: Updating alarm got an error: &errors.ServerError{httpStatus:400, requestId:"B0D06D44-77FC-4881-A2DD-C4F2D846B6FA", hostId:"metrics.cn-hangzhou.aliyuncs.com", errorCode:"MissingComparisonOperator", recommend:"https://error-center.aliyun.com/status/search?Keyword=MissingComparisonOperator&source=PopGw", message:"ComparisonOperator is mandatory for this action.", comment:""}
```  

In addition, the result of plan after applying the script is not clean (without making any changes to the terraform code). The plan result will be something like:
```
alicloud_cms_alarm.cpu_alarm: Modifying... (ID: ************************)
  notify_type: "1" => "0"
```

Although the notify_type was not changed...!

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. `terraform apply` again!

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
Running in a domestic Alicloud account.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
NO

**Comment by firasnajjar** [comment]
I forgot to mention that this started happening only lately. If I run the same terraform script for an alarm that was created ~a month ago, this does not happen. This happens for newly created alarms only.

**Comment by xiaozhu36** [comment]
HI @firasnajjar This issue has been fixed by 1.31.0 and please update and try again. Thanks a lot.

**Comment by firasnajjar** [comment]
Hi @xiaozhu36 

Version 1.31.0 solves this bug but introduces **two new bugs!**

# BUG 1
If you run terraform apply on the exact code above, you'll get an error similar to this:
```
* alicloud_cms_alarm.cpu_alarm: alicloud_cms_alarm.cpu_alarm: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.11
    Resource ID: alicloud_cms_alarm.cpu_alarm
    Mismatch reason: extra attributes: dimensions.instanceId, dimensions.%
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"end_time":*terraform.ResourceAttrDiff{Old:"", New:"24", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "triggered_count":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"tf-cpu_alarm_RDS_postgres_firas", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "contact_groups.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "silence_time":*terraform.ResourceAttrDiff{Old:"", New:"86400", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "notify_type":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "operator":*terraform.ResourceAttrDiff{Old:"", New:">", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "start_time":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "threshold":*terraform.ResourceAttrDiff{Old:"", New:"90", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "statistics":*terraform.ResourceAttrDiff{Old:"", New:"Average", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "project":*terraform.ResourceAttrDiff{Old:"", New:"acs_rds_dashboard", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "metric":*terraform.ResourceAttrDiff{Old:"", New:"CpuUsage", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "contact_groups.0":*terraform.ResourceAttrDiff{Old:"", New:"batata_group", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "status":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"name":*terraform.ResourceAttrDiff{Old:"", New:"tf-cpu_alarm_RDS_postgres_firas", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "contact_groups.0":*terraform.ResourceAttrDiff{Old:"", New:"batata_group", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "silence_time":*terraform.ResourceAttrDiff{Old:"", New:"86400", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "end_time":*terraform.ResourceAttrDiff{Old:"", New:"24", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enabled":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "period":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "notify_type":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "status":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "project":*terraform.ResourceAttrDiff{Old:"", New:"acs_rds_dashboard", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "triggered_count":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "metric":*terraform.ResourceAttrDiff{Old:"", New:"CpuUsage", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "dimensions.%":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "contact_groups.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "operator":*terraform.ResourceAttrDiff{Old:"", New:">", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "start_time":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "statistics":*terraform.ResourceAttrDiff{Old:"", New:"Average", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "threshold":*terraform.ResourceAttrDiff{Old:"", New:"90", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "dimensions.instanceId":*terraform.ResourceAttrDiff{Old:"", New:"pgm-gw8l6v2e656v758f", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

This may be an issue [here](https://github.com/terraform-providers/terraform-provider-alicloud/blob/3049b1240e90402e852aff903e958091e2496b27/alicloud/diff_suppress_funcs.go#L256) where you check the deep equal. It seems that the result from the plan do not include the id of the instance, since it didn't exist yet. When apply is run, the instance exists and its ID is available, this may be causing the diff issue. This is only an assumption.

In addition, if you run `terraform apply` again it will succeed. This seems to be since in this case the result of the plan already has the ID.

# BUG 2
After running: `terraform apply` twice on the same code you'll finally succeed to create the resources. Try now to run: `terraform destroy` and (after a very long time) you'll fail on an error similar to this:
```
....
....
alicloud_db_account.cf_postgres_account: Still destroying... (ID: pgm-gw8l6v2e656v758f:vcap, 4m10s elapsed)
alicloud_db_account.cf_postgres_account: Still destroying... (ID: pgm-gw8l6v2e656v758f:vcap, 4m20s elapsed)
alicloud_db_account.cf_postgres_account: Still destroying... (ID: pgm-gw8l6v2e656v758f:vcap, 4m30s elapsed)
alicloud_db_account.cf_postgres_account: Still destroying... (ID: pgm-gw8l6v2e656v758f:vcap, 4m40s elapsed)
alicloud_db_account.cf_postgres_account: Still destroying... (ID: pgm-gw8l6v2e656v758f:vcap, 4m50s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* alicloud_db_account.cf_postgres_account (destroy): 1 error(s) occurred:

* alicloud_db_account.cf_postgres_account: Delete database account got an error: &errors.ServerError{httpStatus:403, requestId:"D624093E-8793-4C72-8550-D50E069657EF", hostId:"rds.eu-central-1.aliyuncs.com", errorCode:"InstanceEngineType.NotSupport", recommend:"", message:"The instance engine and type does not support operations.", comment:""}.

```

**Comment by xiaozhu36** [comment]
HI  @firasnajjar Bug 1 comes from provider version and retry can fix it. Bug 2 is a product bug. Now, the resource alicloud_db_account only supports [MySQL 5.5/5.6](https://www.terraform.io/docs/providers/alicloud/r/db_account.html#type). Once a pg account was created, it will not be deleted. You can delete with deleting the pg instance. I will contact with product team to fix it.

**Comment by firasnajjar** [comment]
@xiaozhu36 Does this mean that you will be working on fixing bug1? 

Regarding bug 2 the documentation says that alicloud_db_account supports creating only one initial account not multiple ones. This is our case in the terraform provided. We are only creating one.

Bug 2 is also a major issue since it means that automatic tools that create and delete automatically will not work until this is fixed.

**Comment by philippthun** [comment]
> HI @firasnajjar Bug 1 comes from provider version and retry can fix it. Bug 2 is a product bug. Now, the resource alicloud_db_account only supports [MySQL 5.5/5.6](https://www.terraform.io/docs/providers/alicloud/r/db_account.html#type). Once a pg account was created, it will not be deleted. You can delete with deleting the pg instance. I will contact with product team to fix it.

We have two resources at the moment:
```
alicloud_db_account.postgres_account
alicloud_db_instance.postgres
```

To overcome the above mentioned errors during `terraform destroy`, I removed the `alicloud_db_account` from the state file using:
```
terraform state rm -state=<path_to_state_file> "alicloud_db_account.postgres_account"
```

Afterwards running `terraform destroy` succeeded.

@xiaozhu36 - Is this a valid workaround?

**Comment by xiaozhu36** [comment]
HI @philippthun Yes, this is a valid workaround. But we are working on the final solution. Please be patient. Thanks a lot.

**Comment by firasnajjar** [comment]
Is there any progress with BUG 1?

**Comment by xiaozhu36** [comment]
HI @firasnajjar I have removed the `cmsDimensionsDiffSuppressFunc ` by #1057 . You are right and it is redundant.  Thanks for your idea.

**Comment by philippthun** [comment]
@xiaozhu36 - Has **Bug 2** (as described above) been fixed as well?

**Comment by xiaozhu36** [comment]
HI @philippthun The bug2 is related to product design and it need more time to fix. Please be patient. Thanks a lot.

**Comment by KrisPetkov** [comment]
Hello @xiaozhu36 any updates related to **Bug 2**?
Thank you in advance!

**Comment by xiaozhu36** [comment]
HI @KrisPetkov This issue has been fixed and you can check it.

**Comment by KrisPetkov** [comment]
> HI @KrisPetkov This issue has been fixed and you can check it.

Unfortunately I still get similar error. My version of the alicloud provider is 1.60.
My error: 

* alicloud_db_account.db_account (destroy): 1 error(s) occurred:                                                                                                                                                                                                                                                                                                                                                                                                          * alicloud_db_account.db_account: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_account.go:241: Resource pgm-uf67hkjt9j11o5e3:my_account DeleteAccount Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:              SDK.ServerError
--

**Comment by xiaozhu36** [comment]
HI @KrisPetkov What version is your provider? Just now I used the latest 1.63.0 to have a test and it can delete it.

**Comment by KrisPetkov** [comment]
> HI @KrisPetkov What version is your provider? Just now I used the latest 1.63.0 to have a test and it can delete it.

Hi @xiaozhu36 my version is 1.60

**Comment by KrisPetkov** [comment]
Hi @xiaozhu36 I have tried with the newest version 1.63.0 and I'm getting the same error. The only way/workaround is to delete it from the state. Do you have any additional information what could be the issue? Thanks again!

**Comment by xiaozhu36** [comment]
HI @KrisPetkov Can you share me the latest error details?

**Comment by KrisPetkov** [comment]
Hi @xiaozhu36 here is the error:

1 error(s) occurred:                                                                                                                                                                                                                                                                                                                                                                                                                                                    * alicloud_db_account.db_account (destroy): 1 error(s) occurred:                                                                                                                                                                                                                                                                                                                                                                                                        * alicloud_db_account.db_account: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_account.go:243: Resource pgm-uf333v449uf8h4s7:my_account DeleteAccount Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:             SDK.ServerError                                                                                                                                                                                                                     ErrorCode: InstanceEngineType.NotSupport                                                                                                                                                                                            Recommend:                                                                                                                                                                                                                          RequestId: AC333B91-53B2-479E-BE6B-551CEA555CDA                                                                                                                                                                                     Message: The instance engine and type does not support operations.
--

**Comment by KrisPetkov** [comment]
Hi @xiaozhu36 do you have any update on my previous comment?

**Comment by KrisPetkov** [comment]
Hi @xiaozhu36 
Today I tried with the newest version of the provider 1.64.0 and I'm getting similar error to my previous one (The only difference is the row of the error in the .go file):  

Error: Error applying plan:

1 error(s) occurred:

* alicloud_db_account.db_account (destroy): 1 error(s) occurred:

* alicloud_db_account.db_account: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_account.go:243: Resource pgm-uf6u8kaawei88k9g:fss_account DeleteAccount Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InstanceEngineType.NotSupport
Recommend:
RequestId: 53947EA3-ASD4-4F1F-9A51-DFB21D1C8CB5
Message: The instance engine and type does not support operations.

**Comment by KrisPetkov** [comment]
@firasnajjar  can you please reopen the issue? Or I should create a new one?

**Comment by OlegGerber** [comment]
hi @xiaozhu36  Can you please clarify if this issue is resolved or not? 
@KrisPetkov did you created a new issue for this bug? If yes can you please share the issue number? 
Thanks in advance

**Comment by KrisPetkov** [comment]
> hi @xiaozhu36 Can you please clarify if this issue is resolved or not?
> @KrisPetkov did you created a new issue for this bug? If yes can you please share the issue number?
> Thanks in advance

Hi @OlegGerber 
It seems that this is not supported by the AliCloud and it is not a bug/problem in the provider. It's just not supported currently. One workaround is to use the aliyun to delete it.

**Comment by OlegGerber** [comment]
Thanks, @KrisPetkov however for me it sounds like a bug.
@firasnajjar Can you please reopen the ticket?

**Comment by OlegGerber** [comment]
hi @xiaozhu36 ,
Firas can't reopen the ticket since it was closed by you.
Can you please reopen it and provide the fix?
Otherwise, we can't enable the alert feature in terraform.
Thanks in advance.
